export enum itemType {
    Outros = "outros",
    Espada = "espada",
    Machado = "machado",
    Clava = "clava",
    Dobleespada = "dobleespada",
    Adagas = "adagas",
    Cajado = "cajado",
    Varinha = "varinha",
    Arco = "arco",
    Besta = "besta",
    Mosquete = "mosquete",
    Armadura = "armadura",
    Elmo = "elmo",
    Bota = "bota",
    Calca = "calca",
    Anel = "anel",
    Amuleto = "amuleto",
    Pocao = "pocao",
  }  